# Generated by Django 4.2.7 on 2025-12-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activation_space', models.JSONField(blank=True, help_text='Activation space matrix (NxT)', null=True)),
                ('activation_time', models.JSONField(blank=True, help_text='Activation time matrix (8xT)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
            ],
            options={
                'db_table': 'activation_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('signal_data', models.JSONField(help_text='ECG signal amplitudes')),
                ('time_data', models.JSONField(help_text='Time vector in milliseconds')),
                ('n_samples', models.IntegerField()),
                ('p_onset', models.FloatField(help_text='P wave onset (ms)')),
                ('p_peak', models.FloatField(help_text='P wave peak (ms)')),
                ('p_offset', models.FloatField(help_text='P wave offset (ms)')),
                ('qrs_onset', models.FloatField(help_text='QRS complex onset (ms)')),
                ('r_peak', models.FloatField(help_text='R peak (ms)')),
                ('qrs_offset', models.FloatField(help_text='QRS complex offset (ms)')),
                ('t_onset', models.FloatField(help_text='T wave onset (ms)')),
                ('t_offset', models.FloatField(help_text='T wave offset (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecg_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointCloudData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_data', models.JSONField(help_text='Point cloud coordinates (Nx3)')),
                ('n_points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'pointcloud_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('ideal', 'Ideal'), ('eigen', 'Eigen')], default='ideal', max_length=20)),
                ('frame_rate', models.IntegerField(default=30)),
                ('video_file', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Generation time in seconds', null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='activation.activationanalysis')),
            ],
            options={
                'db_table': 'activation_video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activationanalysis',
            name='ecg_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='activation.ecgdata'),
        ),
        migrations.AddField(
            model_name='activationanalysis',
            name='pointcloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='activation.pointclouddata'),
        ),
    ]
