# Generated by Django 4.2.7 on 2025-11-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('sensor_data_id', models.IntegerField(blank=True, null=True)),
                ('sampling_frequency', models.FloatField(default=128.0)),
                ('wavelet_type', models.CharField(default='sym4', max_length=20)),
                ('wavelet_level', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='analysis.analysisjob')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('autocorr_first_min_lag', models.IntegerField(blank=True, null=True)),
                ('autocorr_first_min_value', models.FloatField(blank=True, null=True)),
                ('autocorr_first_peak_lag', models.IntegerField(blank=True, null=True)),
                ('autocorr_first_peak_value', models.FloatField(blank=True, null=True)),
                ('autocorr_decay_rate', models.FloatField(blank=True, null=True)),
                ('autocorr_periodicity_strength', models.FloatField(blank=True, null=True)),
                ('autocorr_data', models.JSONField(blank=True, null=True)),
                ('wavelet_name', models.CharField(default='sym4', max_length=20)),
                ('wavelet_level', models.IntegerField(default=5)),
                ('wavelet_total_energy', models.FloatField(blank=True, null=True)),
                ('wavelet_energy_entropy', models.FloatField(blank=True, null=True)),
                ('wavelet_xcorr_mean', models.FloatField(blank=True, null=True)),
                ('wavelet_xcorr_std', models.FloatField(blank=True, null=True)),
                ('wavelet_xcorr_max', models.FloatField(blank=True, null=True)),
                ('wavelet_xcorr_min', models.FloatField(blank=True, null=True)),
                ('wavelet_data', models.JSONField(blank=True, null=True)),
                ('graph_n_nodes', models.IntegerField(blank=True, null=True)),
                ('graph_n_edges', models.IntegerField(blank=True, null=True)),
                ('graph_density', models.FloatField(blank=True, null=True)),
                ('graph_avg_degree', models.FloatField(blank=True, null=True)),
                ('graph_avg_clustering', models.FloatField(blank=True, null=True)),
                ('graph_n_components', models.IntegerField(blank=True, null=True)),
                ('graph_is_connected', models.BooleanField(blank=True, null=True)),
                ('graph_diameter', models.IntegerField(blank=True, null=True)),
                ('graph_max_degree_centrality', models.FloatField(blank=True, null=True)),
                ('graph_avg_degree_centrality', models.FloatField(blank=True, null=True)),
                ('graph_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_result',
            },
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', '-created_at'], name='analysis_jo_status_bc2820_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['device_id', '-created_at'], name='analysis_jo_device__ed06d2_idx'),
        ),
    ]
